### ISSUE TITLE
NameError in default.py

### ISSUE THREAD

**Issue by ethho** [TACC-Cloud/cc-tapis-v2-actors#5]
```bash
❯ alias tp=tapis
❯ tp actors init
+-------+---------------------------------------------------------------+
| stage | message                                                       |
+-------+---------------------------------------------------------------+
| setup | Project path: ./new_actor                                     |
| setup | CookieCutter variable name=new_actor                          |
| setup | CookieCutter variable project_slug=new_actor                  |
| setup | CookieCutter variable docker_namespace=enho                   |
| setup | CookieCutter variable docker_registry=https://index.docker.io |
| clone | Project path: ./new_actor                                     |
+-------+---------------------------------------------------------------+
❯ cd new_actor
❯ echo '{}' > secrets.json
❯ tp actors deploy
Building enho/new_actor:0.0.1
Finished (9882 msec)
Pushing enho/new_actor:0.0.1
Finished (656 msec)
+--------+----------------------------------------------------------------------+
| stage  | message                                                              |
+--------+----------------------------------------------------------------------+
| build  | Step 1/5 : FROM python:3.7-alpine                                    |
| build  |  ---> 93ac4b41defe                                                   |
|        |                                                                      |
| build  | Step 2/5 : ADD requirements.txt /requirements.txt                    |
| build  |  ---> 487ff1a7f08f                                                   |
|        |                                                                      |
| build  | Step 3/5 : RUN pip3 install -r /requirements.txt                     |
| build  |  ---> Running in 1bd90801458a                                        |
|        |                                                                      |
| build  | Collecting agavepy                                                   |
|        |                                                                      |
| build  |   Downloading agavepy-0.9.5-py2.py3-none-any.whl (183 kB)            |
|        |                                                                      |
| build  | Collecting python-dateutil>=2.4.2                                    |
|        |                                                                      |
| build  |   Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)    |
|        |                                                                      |
| build  | Collecting backports.ssl-match-hostname>=3.4.0.2                     |
|        |                                                                      |
| build  |   Downloading backports.ssl_match_hostname-3.7.0.1.tar.gz (5.7 kB)   |
|        |                                                                      |
| build  | Collecting requests>=2.6.0                                           |
|        |                                                                      |
| build  |   Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)           |
|        |                                                                      |
| build  | Collecting configparser>=3.5.0                                       |
|        |                                                                      |
| build  |   Downloading configparser-5.0.2-py3-none-any.whl (19 kB)            |
|        |                                                                      |
| build  | Collecting cloudpickle>=0.4.0                                        |
|        |                                                                      |
| build  |   Downloading cloudpickle-1.6.0-py3-none-any.whl (23 kB)             |
|        |                                                                      |
| build  | Collecting py>=1.4.26                                                |
|        |                                                                      |
| build  |   Downloading py-1.10.0-py2.py3-none-any.whl (97 kB)                 |
|        |                                                                      |
| build  | Collecting requests-toolbelt>=0.7.1                                  |
|        |                                                                      |
| build  |   Downloading requests_toolbelt-0.9.1-py2.py3-none-any.whl (54 kB)   |
|        |                                                                      |
| build  | Collecting Jinja2>=2.7.3                                             |
|        |                                                                      |
| build  |   Downloading Jinja2-3.0.1-py3-none-any.whl (133 kB)                 |
|        |                                                                      |
| build  | Collecting six>=1.9.0                                                |
|        |                                                                      |
| build  |   Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)                |
|        |                                                                      |
| build  | Collecting future>=0.16.0                                            |
|        |                                                                      |
| build  |   Downloading future-0.18.2.tar.gz (829 kB)                          |
|        |                                                                      |
| build  | Collecting pytest>=2.7.0                                             |
|        |                                                                      |
| build  |   Downloading pytest-6.2.4-py3-none-any.whl (280 kB)                 |
|        |                                                                      |
| build  | Collecting websocket-client==0.53.0                                  |
|        |                                                                      |
| build  |   Downloading websocket_client-0.53.0-py2.py3-none-any.whl (198 kB)  |
|        |                                                                      |
| build  | Collecting MarkupSafe>=2.0                                           |
|        |                                                                      |
| build  |   Downloading MarkupSafe-2.0.1.tar.gz (18 kB)                        |
|        |                                                                      |
| build  | Collecting pluggy<1.0.0a1,>=0.12                                     |
|        |                                                                      |
| build  |   Downloading pluggy-0.13.1-py2.py3-none-any.whl (18 kB)             |
|        |                                                                      |
| build  | Collecting toml                                                      |
|        |                                                                      |
| build  |   Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)               |
|        |                                                                      |
| build  | Collecting packaging                                                 |
|        |                                                                      |
| build  |   Downloading packaging-21.0-py3-none-any.whl (40 kB)                |
|        |                                                                      |
| build  | Collecting iniconfig                                                 |
|        |                                                                      |
| build  |   Downloading iniconfig-1.1.1-py2.py3-none-any.whl (5.0 kB)          |
|        |                                                                      |
| build  | Collecting importlib-metadata>=0.12                                  |
|        |                                                                      |
| build  |   Downloading importlib_metadata-4.6.1-py3-none-any.whl (17 kB)      |
|        |                                                                      |
| build  | Collecting attrs>=19.2.0                                             |
|        |                                                                      |
| build  |   Downloading attrs-21.2.0-py2.py3-none-any.whl (53 kB)              |
|        |                                                                      |
| build  | Collecting typing-extensions>=3.6.4                                  |
|        |                                                                      |
| build  |   Downloading typing_extensions-3.10.0.0-py3-none-any.whl (26 kB)    |
|        |                                                                      |
| build  | Collecting zipp>=0.5                                                 |
|        |                                                                      |
| build  |   Downloading zipp-3.5.0-py3-none-any.whl (5.7 kB)                   |
|        |                                                                      |
| build  | Collecting idna<3,>=2.5                                              |
|        |                                                                      |
| build  |   Downloading idna-2.10-py2.py3-none-any.whl (58 kB)                 |
|        |                                                                      |
| build  | Collecting urllib3<1.27,>=1.21.1                                     |
|        |                                                                      |
| build  |   Downloading urllib3-1.26.6-py2.py3-none-any.whl (138 kB)           |
|        |                                                                      |
| build  | Collecting chardet<5,>=3.0.2                                         |
|        |                                                                      |
| build  |   Downloading chardet-4.0.0-py2.py3-none-any.whl (178 kB)            |
|        |                                                                      |
| build  | Collecting certifi>=2017.4.17                                        |
|        |                                                                      |
| build  |   Downloading certifi-2021.5.30-py2.py3-none-any.whl (145 kB)        |
|        |                                                                      |
| build  | Collecting pyparsing>=2.0.2                                          |
|        |                                                                      |
| build  |   Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)           |
|        |                                                                      |
| build  | Building wheels for collected packages: backports.ssl-match-         |
|        | hostname, future, MarkupSafe                                         |
|        |                                                                      |
| build  |   Building wheel for backports.ssl-match-hostname (setup.py):        |
|        | started                                                              |
|        |                                                                      |
| build  |   Building wheel for backports.ssl-match-hostname (setup.py):        |
|        | finished with status 'done'                                          |
|        |                                                                      |
| build  |   Created wheel for backports.ssl-match-hostname:                    |
|        | filename=backports.ssl_match_hostname-3.7.0.1-py2.py3-none-any.whl   |
|        | size=6757 sha256=5aecf636c41916716db5a61830a5ddfcf84ce424dc1e304f256 |
|        | 2601fb7877233                                                        |
|        |   Stored in directory: /root/.cache/pip/wheels/47/70/47/fa57137a308c |
|        | 61c2891887ba874eec1e0252a857448124896c                               |
|        |                                                                      |
| build  |   Building wheel for future (setup.py): started                      |
|        |                                                                      |
| build  |   Building wheel for future (setup.py): finished with status 'done'  |
|        |                                                                      |
| build  |   Created wheel for future: filename=future-0.18.2-py3-none-any.whl  |
|        | size=491070 sha256=85e8564f88b3142c41f3e3aab4e910f06462ce3f61f14f3e0 |
|        | 2a3a81ba597c026                                                      |
|        |                                                                      |
| build  |   Stored in directory: /root/.cache/pip/wheels/56/b0/fe/4410d17b32f1 |
|        | f0c3cf54cdfb2bc04d7b4b8f4ae377e2229ba0                               |
|        |                                                                      |
| build  |   Building wheel for MarkupSafe (setup.py): started                  |
|        |                                                                      |
| build  |   Building wheel for MarkupSafe (setup.py): finished with status     |
|        | 'done'                                                               |
|        |                                                                      |
| build  |   Created wheel for MarkupSafe: filename=MarkupSafe-2.0.1-py3-none-  |
|        | any.whl size=9761 sha256=0d109b31749eed070542bbab74a0307bba654508eec |
|        | f2ac65559d464ac76b162                                                |
|        |                                                                      |
| build  |   Stored in directory: /root/.cache/pip/wheels/1a/18/04/e3b5bd888f00 |
|        | 0c2716bccc94a565239f9defc47ef93d9e7bea                               |
|        |                                                                      |
| build  | Successfully built backports.ssl-match-hostname future MarkupSafe    |
|        |                                                                      |
| build  | Installing collected packages: zipp, typing-extensions, urllib3,     |
|        | pyparsing, importlib-metadata, idna, chardet, certifi, toml, six,    |
|        | requests, py, pluggy, packaging, MarkupSafe, iniconfig, attrs,       |
|        | websocket-client, requests-toolbelt, python-dateutil, pytest,        |
|        | Jinja2, future, configparser, cloudpickle, backports.ssl-match-      |
|        | hostname, agavepy                                                    |
|        |                                                                      |
| build  | Successfully installed Jinja2-3.0.1 MarkupSafe-2.0.1 agavepy-0.9.5   |
|        | attrs-21.2.0 backports.ssl-match-hostname-3.7.0.1 certifi-2021.5.30  |
|        | chardet-4.0.0 cloudpickle-1.6.0 configparser-5.0.2 future-0.18.2     |
|        | idna-2.10 importlib-metadata-4.6.1 iniconfig-1.1.1 packaging-21.0    |
|        | pluggy-0.13.1 py-1.10.0 pyparsing-2.4.7 pytest-6.2.4 python-         |
|        | dateutil-2.8.1 requests-2.25.1 requests-toolbelt-0.9.1 six-1.16.0    |
|        | toml-0.10.2 typing-extensions-3.10.0.0 urllib3-1.26.6 websocket-     |
|        | client-0.53.0 zipp-3.5.0                                             |
|        |                                                                      |
| build  | WARNING: Running pip as the 'root' user can result in broken         |
|        | permissions and conflicting behaviour with the system package        |
|        | manager. It is recommended to use a virtual environment instead:     |
|        | https://pip.pypa.io/warnings/venv                                    |
|        |                                                                      |
| build  | Removing intermediate container 1bd90801458a                         |
|        |                                                                      |
| build  |  ---> 917bc3426d68                                                   |
|        |                                                                      |
| build  | Step 4/5 : ADD default.py /default.py                                |
| build  |  ---> 3862a5af8ac0                                                   |
|        |                                                                      |
| build  | Step 5/5 : CMD ["python", "/default.py"]                             |
| build  |  ---> Running in 1a0c2b32fff0                                        |
|        |                                                                      |
| build  | Removing intermediate container 1a0c2b32fff0                         |
|        |                                                                      |
| build  |  ---> 14749396d979                                                   |
|        |                                                                      |
| build  | Successfully built 14749396d979                                      |
|        |                                                                      |
| build  | Successfully tagged enho/new_actor:0.0.1                             |
|        |                                                                      |
| push   | The push refers to repository [docker.io/enho/new_actor]             |
| create | Created Tapis actor JVqAo4ELXLAjl                                    |
| cache  | Cached actor identifier to disk                                      |
+--------+----------------------------------------------------------------------+
❯ tp actors run -m 'hello, actor' JVqAo4ELXLAjl
Traceback (most recent call last):
  File "/default.py", line 14, in <module>
    main()
  File "/default.py", line 11, in main
    r.logger.info("Actor received message: {}".format(m))
NameError: name 'r' is not defined
```

**Comment by shwetagopaul92** [comment]
@eho-tacc this should be fixed now.

**Comment by ethho** [comment]
Appears to have fixed `NameError`:

```bash
❯ tp actors init --template default
+-------+---------------------------------------------------------------+
| stage | message                                                       |
+-------+---------------------------------------------------------------+
| setup | Project path: ./new_actor                                     |
| setup | CookieCutter variable name=new_actor                          |
| setup | CookieCutter variable project_slug=new_actor                  |
| setup | CookieCutter variable docker_namespace=enho                   |
| setup | CookieCutter variable docker_registry=https://index.docker.io |
| clone | Project path: ./new_actor                                     |
+-------+---------------------------------------------------------------+
❯ cd new_actor
❯ echo '{}' > secrets.json
❯ tp actors deploy
Building enho/new_actor:0.0.1
Finished (10353 msec)
Pushing enho/new_actor:0.0.1
Finished (8730 msec)
+--------+------------------------------------------------------------------------------------------------------------------+
| stage  | message                                                                                                          |
+--------+------------------------------------------------------------------------------------------------------------------+
| build  | Step 1/5 : FROM python:3.7-alpine                                                                                |
| build  |  ---> 93ac4b41defe                                                                                               |
|        |                                                                                                                  |
| build  | Step 2/5 : ADD requirements.txt /requirements.txt                                                                |
| build  |  ---> d6ab892d27bd                                                                                               |
|        |                                                                                                                  |
| build  | Step 3/5 : RUN pip3 install -r /requirements.txt                                                                 |
| build  |  ---> Running in aaa3c5f8e023                                                                                    |
|        |                                                                                                                  |
| build  | Collecting agavepy                                                                                               |
|        |                                                                                                                  |
| build  |   Downloading agavepy-0.9.5-py2.py3-none-any.whl (183 kB)                                                        |
|        |                                                                                                                  |
| build  | Collecting websocket-client==0.53.0                                                                              |
|        |                                                                                                                  |
| build  |   Downloading websocket_client-0.53.0-py2.py3-none-any.whl (198 kB)                                              |
|        |                                                                                                                  |
| build  | Collecting requests-toolbelt>=0.7.1                                                                              |
|        |                                                                                                                  |
| build  |   Downloading requests_toolbelt-0.9.1-py2.py3-none-any.whl (54 kB)                                               |
|        |                                                                                                                  |
| build  | Collecting python-dateutil>=2.4.2                                                                                |
|        |                                                                                                                  |
| build  |   Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)                                                |
|        |                                                                                                                  |
| build  | Collecting py>=1.4.26                                                                                            |
|        |                                                                                                                  |
| build  |   Downloading py-1.10.0-py2.py3-none-any.whl (97 kB)                                                             |
|        |                                                                                                                  |
| build  | Collecting requests>=2.6.0                                                                                       |
|        |                                                                                                                  |
| build  |   Downloading requests-2.26.0-py2.py3-none-any.whl (62 kB)                                                       |
|        |                                                                                                                  |
| build  | Collecting backports.ssl-match-hostname>=3.4.0.2                                                                 |
|        |                                                                                                                  |
| build  |   Downloading backports.ssl_match_hostname-3.7.0.1.tar.gz (5.7 kB)                                               |
|        |                                                                                                                  |
| build  | Collecting six>=1.9.0                                                                                            |
|        |                                                                                                                  |
| build  |   Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)                                                            |
|        |                                                                                                                  |
| build  | Collecting future>=0.16.0                                                                                        |
|        |                                                                                                                  |
| build  |   Downloading future-0.18.2.tar.gz (829 kB)                                                                      |
|        |                                                                                                                  |
| build  | Collecting configparser>=3.5.0                                                                                   |
|        |                                                                                                                  |
| build  |   Downloading configparser-5.0.2-py3-none-any.whl (19 kB)                                                        |
|        |                                                                                                                  |
| build  | Collecting pytest>=2.7.0                                                                                         |
|        |                                                                                                                  |
| build  |   Downloading pytest-6.2.4-py3-none-any.whl (280 kB)                                                             |
|        |                                                                                                                  |
| build  | Collecting cloudpickle>=0.4.0                                                                                    |
|        |                                                                                                                  |
| build  |   Downloading cloudpickle-1.6.0-py3-none-any.whl (23 kB)                                                         |
|        |                                                                                                                  |
| build  | Collecting Jinja2>=2.7.3                                                                                         |
|        |                                                                                                                  |
| build  |   Downloading Jinja2-3.0.1-py3-none-any.whl (133 kB)                                                             |
|        |                                                                                                                  |
| build  | Collecting MarkupSafe>=2.0                                                                                       |
|        |                                                                                                                  |
| build  |   Downloading MarkupSafe-2.0.1.tar.gz (18 kB)                                                                    |
|        |                                                                                                                  |
| build  | Collecting importlib-metadata>=0.12                                                                              |
|        |                                                                                                                  |
| build  |   Downloading importlib_metadata-4.6.1-py3-none-any.whl (17 kB)                                                  |
|        |                                                                                                                  |
| build  | Collecting attrs>=19.2.0                                                                                         |
|        |                                                                                                                  |
| build  |   Downloading attrs-21.2.0-py2.py3-none-any.whl (53 kB)                                                          |
|        |                                                                                                                  |
| build  | Collecting toml                                                                                                  |
|        |                                                                                                                  |
| build  |   Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)                                                           |
|        |                                                                                                                  |
| build  | Collecting pluggy<1.0.0a1,>=0.12                                                                                 |
|        |                                                                                                                  |
| build  |   Downloading pluggy-0.13.1-py2.py3-none-any.whl (18 kB)                                                         |
|        |                                                                                                                  |
| build  | Collecting packaging                                                                                             |
|        |                                                                                                                  |
| build  |   Downloading packaging-21.0-py3-none-any.whl (40 kB)                                                            |
|        |                                                                                                                  |
| build  | Collecting iniconfig                                                                                             |
|        |                                                                                                                  |
| build  |   Downloading iniconfig-1.1.1-py2.py3-none-any.whl (5.0 kB)                                                      |
|        |                                                                                                                  |
| build  | Collecting zipp>=0.5                                                                                             |
|        |                                                                                                                  |
| build  |   Downloading zipp-3.5.0-py3-none-any.whl (5.7 kB)                                                               |
|        |                                                                                                                  |
| build  | Collecting typing-extensions>=3.6.4                                                                              |
|        |                                                                                                                  |
| build  |   Downloading typing_extensions-3.10.0.0-py3-none-any.whl (26 kB)                                                |
|        |                                                                                                                  |
| build  | Collecting urllib3<1.27,>=1.21.1                                                                                 |
|        |                                                                                                                  |
| build  |   Downloading urllib3-1.26.6-py2.py3-none-any.whl (138 kB)                                                       |
|        |                                                                                                                  |
| build  | Collecting certifi>=2017.4.17                                                                                    |
|        |                                                                                                                  |
| build  |   Downloading certifi-2021.5.30-py2.py3-none-any.whl (145 kB)                                                    |
|        |                                                                                                                  |
| build  | Collecting charset-normalizer~=2.0.0                                                                             |
|        |                                                                                                                  |
| build  |   Downloading charset_normalizer-2.0.1-py3-none-any.whl (35 kB)                                                  |
|        |                                                                                                                  |
| build  | Collecting idna<4,>=2.5                                                                                          |
|        |                                                                                                                  |
| build  |   Downloading idna-3.2-py3-none-any.whl (59 kB)                                                                  |
|        |                                                                                                                  |
| build  | Collecting pyparsing>=2.0.2                                                                                      |
|        |                                                                                                                  |
| build  |   Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)                                                       |
|        |                                                                                                                  |
| build  | Building wheels for collected packages: backports.ssl-match-hostname, future, MarkupSafe                         |
|        |                                                                                                                  |
| build  |   Building wheel for backports.ssl-match-hostname (setup.py): started                                            |
|        |                                                                                                                  |
| build  |   Building wheel for backports.ssl-match-hostname (setup.py): finished with status 'done'                        |
|        |                                                                                                                  |
| build  |   Created wheel for backports.ssl-match-hostname: filename=backports.ssl_match_hostname-3.7.0.1-py2.py3-none-    |
|        | any.whl size=6757 sha256=5ef2bb0540865ae8bfcaa16d80f682e7f5b96501e235f233620a4536a83fc838                        |
|        |                                                                                                                  |
| build  |   Stored in directory: /root/.cache/pip/wheels/47/70/47/fa57137a308c61c2891887ba874eec1e0252a857448124896c       |
|        |                                                                                                                  |
| build  |   Building wheel for future (setup.py): started                                                                  |
|        |                                                                                                                  |
| build  |   Building wheel for future (setup.py): finished with status 'done'                                              |
|        |                                                                                                                  |
| build  |   Created wheel for future: filename=future-0.18.2-py3-none-any.whl size=491070                                  |
|        | sha256=817cd747c8d1bb664f2385f67e3f7ba0559be3a2ff61fed1892a7f18cf693f8d                                          |
|        |   Stored in directory: /root/.cache/pip/wheels/56/b0/fe/4410d17b32f1f0c3cf54cdfb2bc04d7b4b8f4ae377e2229ba0       |
|        |                                                                                                                  |
| build  |   Building wheel for MarkupSafe (setup.py): started                                                              |
|        |                                                                                                                  |
| build  |   Building wheel for MarkupSafe (setup.py): finished with status 'done'                                          |
|        |                                                                                                                  |
| build  |   Created wheel for MarkupSafe: filename=MarkupSafe-2.0.1-py3-none-any.whl size=9761                             |
|        | sha256=e8dac7fdd6fe8b709adbdf18e4a7db64f0611decb3974635e2322340f4b98ecd                                          |
|        |                                                                                                                  |
| build  |   Stored in directory: /root/.cache/pip/wheels/1a/18/04/e3b5bd888f000c2716bccc94a565239f9defc47ef93d9e7bea       |
|        |                                                                                                                  |
| build  | Successfully built backports.ssl-match-hostname future MarkupSafe                                                |
|        |                                                                                                                  |
| build  | Installing collected packages: zipp, typing-extensions, urllib3, pyparsing, importlib-metadata, idna, charset-   |
|        | normalizer, certifi, toml, six, requests, py, pluggy, packaging, MarkupSafe, iniconfig, attrs, websocket-client, |
|        | requests-toolbelt, python-dateutil, pytest, Jinja2, future, configparser, cloudpickle, backports.ssl-match-      |
|        | hostname, agavepy                                                                                                |
|        |                                                                                                                  |
| build  | Successfully installed Jinja2-3.0.1 MarkupSafe-2.0.1 agavepy-0.9.5 attrs-21.2.0 backports.ssl-match-             |
|        | hostname-3.7.0.1 certifi-2021.5.30 charset-normalizer-2.0.1 cloudpickle-1.6.0 configparser-5.0.2 future-0.18.2   |
|        | idna-3.2 importlib-metadata-4.6.1 iniconfig-1.1.1 packaging-21.0 pluggy-0.13.1 py-1.10.0 pyparsing-2.4.7         |
|        | pytest-6.2.4 python-dateutil-2.8.1 requests-2.26.0 requests-toolbelt-0.9.1 six-1.16.0 toml-0.10.2 typing-        |
|        | extensions-3.10.0.0 urllib3-1.26.6 websocket-client-0.53.0 zipp-3.5.0                                            |
|        |                                                                                                                  |
| build  | WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the      |
|        | system package manager. It is recommended to use a virtual environment instead:                                  |
|        | https://pip.pypa.io/warnings/venv                                                                                |
|        |                                                                                                                  |
| build  | Removing intermediate container aaa3c5f8e023                                                                     |
|        |                                                                                                                  |
| build  |  ---> 8242e4835c2e                                                                                               |
|        |                                                                                                                  |
| build  | Step 4/5 : ADD default.py /default.py                                                                            |
| build  |  ---> 3ca67c82d1bf                                                                                               |
|        |                                                                                                                  |
| build  | Step 5/5 : CMD ["python", "/default.py"]                                                                         |
| build  |  ---> Running in 78651a11263c                                                                                    |
|        |                                                                                                                  |
| build  | Removing intermediate container 78651a11263c                                                                     |
|        |                                                                                                                  |
| build  |  ---> 8fdb012c0ef5                                                                                               |
|        |                                                                                                                  |
| build  | Successfully built 8fdb012c0ef5                                                                                  |
|        |                                                                                                                  |
| build  | Successfully tagged enho/new_actor:0.0.1                                                                         |
|        |                                                                                                                  |
| push   | The push refers to repository [docker.io/enho/new_actor]                                                         |
| push   | 0.0.1: digest: sha256:e0baf2d8e2e0d5b6afbe3d4bb955fa44c9a8eef33f1245a6954b021563c55c73 size: 1994                |
| create | Created Tapis actor Wxwx0VWvM7QgM                                                                                |
| cache  | Cached actor identifier to disk                                                                                  |
+--------+------------------------------------------------------------------------------------------------------------------+
❯ watch -n 20 tapis actors list
❯ tp actors run -m 'hello, actor' Wxwx0VWvM7QgM
Message failed or timed out: [Errno 502] Bad Gateway for https://api.tacc.utexas.edu//actors/v2/Wxwx0VWvM7QgM/messages?_abaco_synchronous=True: '{\n    "status": "error",\n    "message": "Timeout error waiting on Abaco service response. The server may be busy or overloaded.",\n    "version": "unknown",\n    "result": None\n}\n'
❯ tp actors execs list Wxwx0VWvM7QgM
+---------------+----------+
| executionId   | status   |
+---------------+----------+
| Q1yYQebxox7jq | COMPLETE |
+---------------+----------+
❯ tp actors execs logs Wxwx0VWvM7QgM Q1yYQebxox7jq
Logs for execution Q1yYQebxox7jq
 {'raw_message': 'hello, actor', 'content_type': None, 'execution_id': 'Q1yYQebxox7jq', 'username': 'eho', 'state': '{}', 'actor_dbid': 'TACC-PROD_Wxwx0VWvM7QgM', 'actor_id': 'Wxwx0VWvM7QgM', 'raw_message_parse_log': 'Error parsing message: malformed node or string: <_ast.Name object at 0x7f4e0e8f7b10>', 'message_dict': {}, 'PATH': '/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', 'HOSTNAME': '29df21007e6c', '_abaco_synchronous': 'True', '_abaco_username': 'eho', '_abaco_api_server': 'https://api.tacc.utexas.edu', '_abaco_jwt_header_name': 'X-Jwt-Assertion-Tacc-Prod', '_abaco_execution_id': 'Q1yYQebxox7jq', '_abaco_Content_Type': 'str', '_abaco_actor_revision': '1', '_abaco_access_token': '6ff48302b44d2ec3cbaecbb2e7d5177', '_abaco_actor_dbid': 'TACC-PROD_Wxwx0VWvM7QgM', '_abaco_actor_id': 'Wxwx0VWvM7QgM', '_abaco_worker_id': 'NrvylPPR8z1Ae', '_abaco_container_repo': 'enho/new_actor:0.0.1', '_abaco_actor_state': '{}', '_abaco_actor_name': 'new_actor', '_actor_configs': '{}', 'MSG': 'hello, actor', 'LANG': 'C.UTF-8', 'GPG_KEY': '0D96DF4D4110E5C43FBFB17F2D347EA6AA65421D', 'PYTHON_VERSION': '3.7.11', 'PYTHON_PIP_VERSION': '21.1.3', 'PYTHON_GET_PIP_URL': 'https://github.com/pypa/get-pip/raw/a1675ab6c2bd898ed82b1f58c486097f763c74a9/public/get-pip.py', 'PYTHON_GET_PIP_SHA256': '6665659241292b2147b58922b9ffe11dda66b39d52d8a6f3aa310bc1d60ea6f7', 'HOME': '/'}
Actor received message: hello, actor
```
